document.body.classList.add('login-mode');
const cfg=window.APP_CONFIG;
const db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);let user=null,records=[],dirty=new Map(),opening=false,currentPage=1,pageSize=500,totalRecords=0;
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0});
function showLogin(msg=''){$('app').hidden=true;$('app').style.display='none';$('login').hidden=false;$('login').style.display='grid';$('login').classList.remove('login-success');document.body.classList.add('login-mode');$('loginMsg').textContent=msg;const b=$('signInBtn');b.disabled=false;b.textContent='Sign In Securely'}
async function showDashboard(session){if(opening||!session?.user)return;opening=true;user=session.user;$('login').classList.add('login-success');setTimeout(async()=>{$('login').hidden=true;$('login').style.display='none';$('app').hidden=false;$('app').style.display='block';$('app').classList.add('app-enter');document.body.classList.remove('login-mode');$('welcome').textContent='Signed in: '+user.email;window.scrollTo(0,0);await loadRecords();opening=false},450)}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();e.stopPropagation();const b=$('signInBtn');b.disabled=true;b.textContent='Signing In...';$('loginMsg').textContent='Checking secure access...';const {data,error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('loginMsg').textContent=error.message;b.disabled=false;b.textContent='Sign In Securely';return}if(data.session)showDashboard(data.session)});
db.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||!session){if(event==='SIGNED_OUT')showLogin('Signed out successfully.')}else if(['SIGNED_IN','INITIAL_SESSION','TOKEN_REFRESHED'].includes(event))showDashboard(session)});
async function loadRecords(){const start=(currentPage-1)*pageSize,end=start+pageSize-1;$('dataMsg').textContent='Loading records...';const {data,error,count}=await db.from('audit_records').select('*',{count:'exact'}).order('updated_at',{ascending:false}).range(start,end);if(error){$('dataMsg').textContent='Data error: '+error.message;return}records=data||[];totalRecords=count||0;render();updatePager()}
function safe(v){return String(v??'').replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]))}
function render(){const sum=k=>records.reduce((a,r)=>a+Number(r[k]||0),0),audited=records.filter(r=>r.audit_checked).length,pending=records.length-audited;$('recordCount').textContent=totalRecords.toLocaleString('en-IN');$('pendingCount').textContent=pending;$('auditedCount').textContent=audited;$('orderValue').textContent=money(sum('order_amount'));$('invoiceValue').textContent=money(sum('invoice_amount'));$('differenceValue').textContent=money(sum('amount_difference'));$('averageDiscount').textContent=(records.length?sum('discount_percent')/records.length:0).toFixed(2)+'%';$('dataMsg').textContent=`Showing ${records.length.toLocaleString('en-IN')} records from ${totalRecords.toLocaleString('en-IN')} total`;$('rows').innerHTML=records.map(r=>`<tr><td><input type="checkbox" ${r.audit_checked?'checked':''} onchange="edit(${r.id},'audit_checked',this.checked)"></td><td>${safe(r.sales_order)}</td><td>${safe(r.invoice_no)}</td><td>${safe(r.customer)}</td><td>${safe(r.salesman)}</td><td>${safe(r.item)}</td><td><input value="${Number(r.discount_percent||0)}" type="number" step=".01" onchange="edit(${r.id},'discount_percent',this.value)"></td><td><select onchange="edit(${r.id},'status',this.value)">${['Pending','Reviewed','Correction Required','Resolved'].map(x=>`<option ${r.status===x?'selected':''}>${x}</option>`).join('')}</select></td><td><input value="${safe(r.comments)}" onchange="edit(${r.id},'comments',this.value)"></td><td><button onclick="save(${r.id})">Save</button></td></tr>`).join('')}
function updatePager(){const pages=Math.max(1,Math.ceil(totalRecords/pageSize));$('pageInformation').textContent=`Page ${currentPage} of ${pages} • ${totalRecords.toLocaleString('en-IN')} total`;$('previousPage').disabled=currentPage<=1;$('nextPage').disabled=currentPage>=pages}
window.edit=(id,key,val)=>{let r={...(dirty.get(id)||records.find(x=>x.id===id))};r[key]=val;dirty.set(id,r);$('unsaved').textContent=dirty.size+' unsaved'};
window.save=async id=>{const r=dirty.get(id);if(!r)return;const {error}=await db.from('audit_records').update({audit_checked:!!r.audit_checked,status:r.status,comments:r.comments,discount_percent:Number(r.discount_percent||0),updated_by:user.id,updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);dirty.delete(id);$('unsaved').textContent=dirty.size+' unsaved';await loadRecords()};
$('previousPage').onclick=async()=>{if(currentPage>1){currentPage--;await loadRecords();scrollTo(0,0)}};$('nextPage').onclick=async()=>{if(currentPage<Math.ceil(totalRecords/pageSize)){currentPage++;await loadRecords();scrollTo(0,0)}};$('pageSize').onchange=async function(){pageSize=Number(this.value);currentPage=1;await loadRecords()};$('refreshBtn').onclick=loadRecords;$('logoutBtn').onclick=async()=>{await db.auth.signOut();showLogin('Signed out successfully.')};db.auth.getSession().then(({data,error})=>{if(error)showLogin(error.message);else if(data.session)showDashboard(data.session);else showLogin()});
