document.body.classList.add("login-mode");const cfg=window.APP_CONFIG;if(!cfg||cfg.SUPABASE_PUBLISHABLE_KEY.includes('PASTE_'))alert('Open config.js and paste your Supabase publishable key. Never paste a secret key.');const db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});let records=[],dirty=new Map(),view='updates',user=null;const $=id=>document.getElementById(id),money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0});function toast(m,bad=false){let t=$('toast');t.textContent=m;t.style.background=bad?'#7f1d1d':'#14532d';t.style.display='block';setTimeout(()=>t.style.display='none',2600)}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMsg').textContent='';let {data,error}=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if (error) {
$('loginMsg').textContent = error.message;
return;
}
 
$('loginMsg').textContent = 'Opening secure workspace...';
$('login').classList.add('login-success');
 
setTimeout(() => {
enter(data.user);
}, 650);};$('logoutBtn').onclick=async()=>{await db.auth.signOut();location.reload()};async function enter(u) {
user = u;
 
$('login').hidden = true;
document.body.classList.remove('login-mode');
 
$('app').hidden = false;
$('app').classList.add('app-enter');
 
window.scrollTo(0, 0);
 
$('welcome').textContent = 'Signed in: ' + u.email;
 
await load();
}$('welcome').textContent='Signed in: '+u.email;await load()}
async function load(){let {data,error}=await db.from('audit_records').select('*').order('updated_at',{ascending:false});if(error)return toast(error.message,true);records=data||[];dirty.clear();fillFilters();render()}
function fillFilters(){for(let [id,key,label] of [['branch','branch','All Branches'],['salesman','salesman','All Salespeople']]){let el=$(id),v=el.value;el.innerHTML=`<option value="">${label}</option>`+[...new Set(records.map(r=>r[key]).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('');el.value=v}}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function filtered(){let q=$('search').value.toLowerCase(),b=$('branch').value,s=$('salesman').value,st=$('status').value,d=$('fromDate').value;return records.filter(r=>(view!='updates'||r.audit_checked!==true)&&(!q||[r.sales_order,r.invoice_no,r.customer,r.salesman,r.item].join(' ').toLowerCase().includes(q))&&(!b||r.branch==b)&&(!s||r.salesman==s)&&(!st||r.status==st)&&(!d||String(r.updated_at).slice(0,10)>=d))}
function render(){if(view==='history')return renderHistory();let a=filtered(),sum=k=>a.reduce((x,r)=>x+Number(r[k]||0),0),avg=k=>a.length?sum(k)/a.length:0,reviewed=a.filter(r=>r.audit_checked).length;let vals=[['Visible Records',a.length,'#22d3ee'],['Order Value',money(sum('order_amount')),'#8b5cf6'],['Invoice Value',money(sum('invoice_amount')),'#22c55e'],['Net Difference',money(sum('amount_difference')),'#f59e0b'],['Audited',reviewed,'#14b8a6'],['Average Discount',avg('discount_percent').toFixed(2)+'%','#ec4899']];$('cards').innerHTML=vals.map(x=>`<div class="kpi" style="--c:${x[2]}"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');let counts={};a.forEach(r=>counts[r.status||'Pending']=(counts[r.status||'Pending']||0)+1);$('summary').innerHTML=Object.entries(counts).map(([k,v])=>`<div><span>${esc(k)}</span><b>${v}</b></div>`).join('')||'<div>No visible records</div>';function group(key){let o={};a.forEach(r=>{let k=r[key]||'Not assigned';(o[k]??=[]).push(Number(r.discount_percent||0))});return Object.entries(o).map(([k,v])=>[k,v.reduce((x,y)=>x+y,0)/v.length]).sort((x,y)=>y[1]-x[1]).slice(0,4)}$('discountSummary').innerHTML=[...group('item').slice(0,2),...group('customer').slice(0,1),...group('salesman').slice(0,1)].map(([k,v])=>`<div><span>${esc(k).slice(0,28)}</span><b>${v.toFixed(2)}%</b></div>`).join('');$('rows').innerHTML=a.map(rowHtml).join('');$('dirtyCount').textContent=dirty.size+' unsaved'}
function rowHtml(r){let d=dirty.get(r.id)||r;return `<tr data-id="${r.id}" class="${dirty.has(r.id)?'edited':''}"><td><input class="edit audit_checked" type="checkbox" ${d.audit_checked?'checked':''}></td><td><select class="edit status">${['Pending','Reviewed','Correction Required','Resolved'].map(x=>`<option ${d.status==x?'selected':''}>${x}</option>`).join('')}</select></td><td>${esc(r.sales_order)}</td><td>${esc(r.invoice_no)}</td><td>${esc(r.customer)}</td><td>${esc(r.salesman)}</td><td>${esc(r.item)}</td><td>${money(r.order_amount)}</td><td>${money(r.invoice_amount)}</td><td>${money(r.amount_difference)}</td><td><input class="edit discount_percent" type="number" step="0.01" value="${Number(d.discount_percent||0)}"></td><td><input class="edit discount_amount" type="number" step="0.01" value="${Number(d.discount_amount||0)}"></td><td><input class="edit comments" value="${esc(d.comments)}"></td><td><button onclick="saveOne(${r.id})" class="primary">Save</button></td></tr>`}
document.addEventListener('change',e=>{if(!e.target.classList.contains('edit'))return;let tr=e.target.closest('tr'),id=Number(tr.dataset.id),base={...records.find(x=>x.id===id)},field=[...e.target.classList].find(x=>x!='edit');base[field]=e.target.type==='checkbox'?e.target.checked:e.target.value;dirty.set(id,base);tr.classList.add('edited');$('dirtyCount').textContent=dirty.size+' unsaved'});document.addEventListener('input',e=>{if(e.target.classList.contains('edit'))e.target.dispatchEvent(new Event('change',{bubbles:true}))});
async function saveOne(id){let n=dirty.get(id);if(!n)return toast('No changes to save');let old=records.find(x=>x.id===id),payload={status:n.status,comments:n.comments,discount_percent:Number(n.discount_percent||0),discount_amount:Number(n.discount_amount||0),audit_checked:!!n.audit_checked,updated_at:new Date().toISOString(),updated_by:user.id};let {error}=await db.from('audit_records').update(payload).eq('id',id);if(error)return toast(error.message,true);await db.from('audit_history').insert({record_id:id,old_status:old.status,new_status:payload.status,comment:payload.comments,updated_by:user.email});dirty.delete(id);toast('Saved successfully');await load()}window.saveOne=saveOne;$('saveAllBtn').onclick=async()=>{for(let id of [...dirty.keys()])await saveOne(id)};$('refreshBtn').onclick=load;['search','branch','salesman','status','fromDate'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;$('tableTitle').textContent=b.textContent;render()});async function renderHistory(){let {data,error}=await db.from('audit_history').select('*').order('updated_at',{ascending:false}).limit(500);if(error)return toast(error.message,true);$('cards').innerHTML='';$('summary').innerHTML='';$('discountSummary').innerHTML='';$('rows').innerHTML=(data||[]).map(x=>`<tr><td colspan="2">${esc(x.updated_at)}</td><td colspan="2">Record ${x.record_id}</td><td colspan="3">${esc(x.old_status)} → ${esc(x.new_status)}</td><td colspan="4">${esc(x.updated_by)}</td><td colspan="3">${esc(x.comment)}</td></tr>`).join('')}
window.addEventListener('beforeunload',e=>{if(dirty.size){e.preventDefault();e.returnValue=''}});db.auth.getSession().then(({data})=>{if(data.session)enter(data.session.user)});db.channel('audit-live').on('postgres_changes',{event:'*',schema:'public',table:'audit_records'},()=>{if(!dirty.size)load()}).subscribe();