document.body.classList.add("login-mode");
const cfg=window.APP_CONFIG;
const db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id); let user=null,records=[],dirty=new Map();
function message(text,bad=false){$('loginMsg').textContent=text;$('loginMsg').style.color=bad?'#fca5a5':'#67e8f9'}
$('loginForm').addEventListener('submit',async(event)=>{event.preventDefault();const btn=$('signInBtn');btn.disabled=true;btn.textContent='Signing In...';message('Checking secure access...');try{const {data,error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)throw error;if(!data?.user)throw new Error('User session was not received');message('Opening secure workspace...');$('login').classList.add('login-success');setTimeout(()=>openDashboard(data.user),650)}catch(error){console.error(error);message(error.message||'Unable to sign in',true);btn.disabled=false;btn.textContent='Sign In Securely'}});
async function openDashboard(currentUser){user=currentUser;$('login').hidden=true;$('login').style.display='none';document.body.classList.remove('login-mode');$('app').hidden=false;$('app').style.display='block';$('app').classList.add('app-enter');$('welcome').textContent='Signed in: '+currentUser.email;window.scrollTo(0,0);await loadRecords()}
async function loadRecords(){const {data,error}=await db.from('audit_records').select('*').order('updated_at',{ascending:false});if(error){$('dataMsg').textContent='Data error: '+error.message;return}records=data||[];render()}
function render(){$('dataMsg').textContent=records.length?records.length+' audit records loaded':'Login successful. No records are currently available in audit_records.';$('recordCount').textContent=records.length;$('rows').innerHTML=records.slice(0,500).map(r=>`<tr><td><input type="checkbox" ${r.audit_checked?'checked':''} onchange="edit(${r.id},'audit_checked',this.checked)"></td><td>${safe(r.sales_order)}</td><td>${safe(r.invoice_no)}</td><td>${safe(r.customer)}</td><td>${safe(r.salesman)}</td><td>${safe(r.item)}</td><td><input value="${Number(r.discount_percent||0)}" type="number" step=".01" onchange="edit(${r.id},'discount_percent',this.value)"></td><td><select onchange="edit(${r.id},'status',this.value)">${['Pending','Reviewed','Correction Required','Resolved'].map(x=>`<option ${r.status===x?'selected':''}>${x}</option>`).join('')}</select></td><td><input value="${safe(r.comments)}" onchange="edit(${r.id},'comments',this.value)"></td><td><button onclick="save(${r.id})">Save</button></td></tr>`).join('')}
function safe(v){return String(v??'').replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]))}window.edit=(id,key,val)=>{let r={...(dirty.get(id)||records.find(x=>x.id===id))};r[key]=val;dirty.set(id,r);$('unsaved').textContent=dirty.size+' unsaved'};window.save=async id=>{let r=dirty.get(id);if(!r)return;const payload={audit_checked:!!r.audit_checked,status:r.status,comments:r.comments,discount_percent:Number(r.discount_percent||0),updated_by:user.id,updated_at:new Date().toISOString()};const {error}=await db.from('audit_records').update(payload).eq('id',id);if(error)return alert(error.message);dirty.delete(id);$('unsaved').textContent=dirty.size+' unsaved';await loadRecords()};
$('logoutBtn').onclick=async()=>{await db.auth.signOut();location.reload()};$('refreshBtn').onclick=loadRecords;db.auth.getSession().then(({data})=>{if(data?.session?.user)openDashboard(data.session.user)}).catch(console.error);
